# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish packages

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build bundle and publish to npmjs.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ matrix.node }}
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies ${{ matrix.node }}
        uses: action/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-$ {{ matrix.node }}
        run: |
          npm ci
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
